name: "Test All Assertions"

on:
  push:
    branches:
      - "**"

jobs:
  test-all-assertions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npm run test --workspaces
