name: "Test All Assertions"

on:
  push:
    branches:
      - "**"

jobs:
  unit-test-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npm run test --workspaces
  test-directory-exists:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pr-mpt/actions-assert@v1
        with:
          assertion: "workflows://./../../packages/directory-exists"
          expected: "packages"
